services:
  - type: web
    name: flask-app-docker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        value: "tu_clave_secreta"
      - key: RECAPTCHA_PUBLIC_KEY
        value: "tu_site_key"
      - key: RECAPTCHA_SECRET_KEY
        value: "tu_secret_key"
