services:
  - type: web
    name: registro-estudiantes-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: "una_clave_secreta"
      - key: MAIL_USERNAME
        value: "tucorreo@gmail.com"
      - key: MAIL_PASSWORD
        value: "tu_clave_app"
      - key: RECAPTCHA_SECRET_KEY
        value: "clave_de_tu_recaptcha"
